services:
  - type: web
    name: mortgage-client
    env: static
    staticPublishPath: dist/mortgage-client
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist/mortgage-client
    envVars:
      - key: API_URL
        value: https://mortgage-server.onrender.com
